import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';

import { UserButton } from "@clerk/nextjs";


const outFit = Outfit({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${outFit} antialiased`}
      >

        {children}

      </body>
    </html>
    </ClerkProvider>
  );
}
